# fly.toml app configuration file generated for jordanb on 2023-05-15T20:23:46-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jordanb"
primary_region = "scl"

[env]
  start_command = "node index.js"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

